# Generated by Django 3.2.3 on 2021-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_at', models.DateTimeField(auto_now_add=True)),
                ('date_update_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('content', models.TextField(max_length=10000)),
                ('description', models.TextField(max_length=5000)),
            ],
        ),
    ]
